crystal_logistics:
  services:
    catalogue:
      uri: http://localhost:8081
      username: catalogue_service_user
      password: password
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/manager
    username: postgres
    password: 1496
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/crystal_logistics
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: manager-app
            client-secret: Sxlk3JJkevl6gI9bshDKo31YBiNM6KFI
            scope:
              - edit_catalogue
              - view_catalogue
              - openid
              - microprofile-jwt

