spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/catalogue
    username: postgres
    password: 1496
  flyway:
    schemas:
      -public
      -catalogue
  jpa:
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/crystal_logistics
server:
  port: 8081
logging:
  level:
    sql: info